# __init__.py — re-exports subset of models for backward compatibility.
# All models still importable from app.models.entities too.
from __future__ import annotations

from app.models.entities import (
    Attachment,
    AuditLog,
    BreakEntry,
    ChatThread,
    ChatThreadParticipantGroup,
    ChatThreadParticipantRole,
    ChatThreadParticipantUser,
    ClockEntry,
    ConstructionReport,
    MaterialCatalogImportState,
    MaterialCatalogItem,
    EmployeeGroup,
    EmployeeGroupMember,
    JobTicket,
    Message,
    Project,
    ProjectMember,
    Site,
    Task,
    TaskAssignment,
    User,
    WikiPage,
)

__all__ = [
    "Attachment",
    "AuditLog",
    "BreakEntry",
    "ChatThread",
    "ChatThreadParticipantGroup",
    "ChatThreadParticipantRole",
    "ChatThreadParticipantUser",
    "ClockEntry",
    "ConstructionReport",
    "MaterialCatalogImportState",
    "MaterialCatalogItem",
    "EmployeeGroup",
    "EmployeeGroupMember",
    "JobTicket",
    "Message",
    "Project",
    "ProjectMember",
    "Site",
    "Task",
    "TaskAssignment",
    "User",
    "WikiPage",
]
