# api.py -- backward-compatibility re-export shim.
# All schema classes now live in their respective domain files.
# This file re-exports everything so existing imports continue to work.
from __future__ import annotations

from app.schemas.auth import (
    InviteAccept,
    InviteCreate,
    InviteDispatchOut,
    PasswordResetConfirm,
    PasswordResetDispatchOut,
)
from app.schemas.chat import (
    MessageAttachmentOut,
    MessageCreate,
    MessageOut,
    ThreadCreate,
    ThreadOut,
    ThreadUpdate,
)
from app.schemas.files import ProjectFolderCreate, ProjectFolderOut
from app.schemas.materials import (
    MaterialCatalogImportStateOut,
    MaterialCatalogItemOut,
    ProjectMaterialNeedCreate,
    ProjectMaterialNeedOut,
    ProjectMaterialNeedUpdate,
    ProjectTrackedMaterialOut,
)
from app.schemas.notification import NotificationOut
from app.schemas.project import (
    ProjectActivityOut,
    ProjectClassTaskTemplateOut,
    ProjectClassTemplateOut,
    ProjectCreate,
    ProjectFinanceOut,
    ProjectFinanceUpdate,
    ProjectImportStatsOut,
    ProjectOfficeNoteOut,
    ProjectOut,
    ProjectOverviewOut,
    ProjectUpdate,
    ProjectWeatherDayOut,
    ProjectWeatherOut,
)
from app.schemas.report import (
    ConstructionReportCreate,
    ConstructionReportExtra,
    ConstructionReportMaterial,
    ConstructionReportPayload,
    ConstructionReportWorker,
    RecentConstructionReportOut,
)
from app.schemas.settings import (
    UpdateInstallOut,
    UpdateInstallRequest,
    UpdateStatusOut,
    WeatherSettingsOut,
    WeatherSettingsUpdate,
)
from app.schemas.site import JobTicketCreate, JobTicketOut, SiteCreate, SiteOut
from app.schemas.task import (
    PlanningAbsenceOut,
    PlanningDayOut,
    PlanningWeekOut,
    TaskCreate,
    TaskOut,
    TaskUpdate,
)
from app.schemas.team import (
    EmployeeGroupCreate,
    EmployeeGroupMemberOut,
    EmployeeGroupOut,
    EmployeeGroupUpdate,
)
from app.schemas.time import (
    BreakAction,
    ClockOut,
    RequiredDailyHoursOut,
    RequiredDailyHoursUpdate,
    SchoolAbsenceCreate,
    SchoolAbsenceOut,
    TimeCurrentOut,
    TimeEntryOut,
    TimeEntryUpdate,
    TimesheetOut,
    VacationRequestCreate,
    VacationRequestOut,
    VacationRequestReview,
)
from app.schemas.user import (
    AssignableUserOut,
    LoginRequest,
    NicknameAvailabilityOut,
    ProfileUpdate,
    UserCreate,
    UserOut,
    UserUpdate,
)
from app.schemas.wiki import WikiLibraryFileOut, WikiPageCreate, WikiPageOut, WikiPageUpdate

__all__ = [
    "LoginRequest",
    "UserCreate",
    "UserUpdate",
    "UserOut",
    "AssignableUserOut",
    "ProfileUpdate",
    "NicknameAvailabilityOut",
    "EmployeeGroupMemberOut",
    "EmployeeGroupOut",
    "EmployeeGroupCreate",
    "EmployeeGroupUpdate",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectOut",
    "ProjectFinanceUpdate",
    "ProjectFinanceOut",
    "ProjectActivityOut",
    "ProjectOfficeNoteOut",
    "ProjectOverviewOut",
    "ProjectWeatherDayOut",
    "ProjectWeatherOut",
    "ProjectClassTaskTemplateOut",
    "ProjectClassTemplateOut",
    "ProjectImportStatsOut",
    "NotificationOut",
    "MaterialCatalogItemOut",
    "MaterialCatalogImportStateOut",
    "ProjectMaterialNeedOut",
    "ProjectMaterialNeedUpdate",
    "ProjectMaterialNeedCreate",
    "ProjectTrackedMaterialOut",
    "TaskCreate",
    "TaskUpdate",
    "TaskOut",
    "PlanningAbsenceOut",
    "PlanningDayOut",
    "PlanningWeekOut",
    "ProjectFolderCreate",
    "ProjectFolderOut",
    "SiteCreate",
    "SiteOut",
    "JobTicketCreate",
    "JobTicketOut",
    "ThreadCreate",
    "ThreadUpdate",
    "ThreadOut",
    "MessageCreate",
    "MessageAttachmentOut",
    "MessageOut",
    "WikiPageCreate",
    "WikiPageUpdate",
    "WikiPageOut",
    "WikiLibraryFileOut",
    "ConstructionReportWorker",
    "ConstructionReportMaterial",
    "ConstructionReportExtra",
    "ConstructionReportPayload",
    "ConstructionReportCreate",
    "RecentConstructionReportOut",
    "ClockOut",
    "BreakAction",
    "TimesheetOut",
    "TimeCurrentOut",
    "TimeEntryOut",
    "TimeEntryUpdate",
    "RequiredDailyHoursUpdate",
    "RequiredDailyHoursOut",
    "VacationRequestCreate",
    "VacationRequestReview",
    "VacationRequestOut",
    "SchoolAbsenceCreate",
    "SchoolAbsenceOut",
    "InviteCreate",
    "InviteDispatchOut",
    "PasswordResetDispatchOut",
    "InviteAccept",
    "PasswordResetConfirm",
    "WeatherSettingsOut",
    "WeatherSettingsUpdate",
    "UpdateStatusOut",
    "UpdateInstallRequest",
    "UpdateInstallOut",
]
