/**
 * How a flat list of stored files becomes the folder groups the browser
 * shows — and the small facts a row or tile states about a file.
 *
 * Pure, so the project tab, the customer card and the tests reason about the
 * same grouping without a component around it. Order matters here: the
 * sequence a click hands to the viewer is exactly the order these helpers
 * produce.
 */
import { isImageType } from "../../utils/filePreview";
import type { Language, StoredFile } from "../../types";

/** The key of files with no folder; sorts first and is labelled, never shown raw. */
export const ROOT_FOLDER = "/";

export type FolderGroup = { folder: string; files: StoredFile[] };

export function folderKeyOf(file: StoredFile): string {
  return (file.folder ?? "").trim() || ROOT_FOLDER;
}

export function folderLabel(folder: string, language: Language): string {
  if (folder !== ROOT_FOLDER) return folder;
  return language === "de" ? "Hauptordner" : "Root";
}

/** Report folders are generated by the server; the browser hints at that. */
export function isReportFolder(folder: string): boolean {
  const f = folder.toLowerCase();
  return f.includes("bericht") || f.includes("report");
}

/**
 * Root first, then folders alphabetically; inside a group the rows keep the
 * order they arrived in (newest first from the API).
 */
export function groupFilesByFolder(rows: readonly StoredFile[]): FolderGroup[] {
  const byFolder = new Map<string, StoredFile[]>();
  for (const file of rows) {
    const key = folderKeyOf(file);
    byFolder.set(key, [...(byFolder.get(key) ?? []), file]);
  }
  return Array.from(byFolder.entries())
    .sort(([a], [b]) => {
      if (a === ROOT_FOLDER) return -1;
      if (b === ROOT_FOLDER) return 1;
      return a.localeCompare(b);
    })
    .map(([folder, files]) => ({ folder, files }));
}

/** The groups' files in display order — what "next" in the viewer follows. */
export function flattenGroups(groups: readonly FolderGroup[]): StoredFile[] {
  return groups.flatMap((group) => group.files);
}

/**
 * The search the project tab always had (App's `fileRows`): name, folder or
 * stored path, case-insensitively. Kept identical so a customer-page search
 * finds what a project-tab search finds.
 */
export function filterFilesByQuery(rows: readonly StoredFile[], query: string): StoredFile[] {
  const needle = query.trim().toLowerCase();
  if (!needle) return [...rows];
  return rows.filter(
    (file) =>
      String(file.file_name).toLowerCase().includes(needle) ||
      String(file.folder ?? "").toLowerCase().includes(needle) ||
      String(file.path ?? "").toLowerCase().includes(needle),
  );
}

export function fileTypeLabel(contentType: string): string {
  const ct = contentType ?? "";
  if (ct.startsWith("image/")) return ct.replace("image/", "");
  if (ct === "application/pdf") return "PDF";
  if (ct.startsWith("text/")) return ct.replace("text/", "");
  return ct;
}

export function isImageFile(file: StoredFile): boolean {
  return isImageType(file.content_type ?? "");
}

/**
 * One glyph per content-type family for tiles that have no thumbnail. Kept
 * conservative on the detection — "📎" for the unknown case rather than a
 * confident wrong guess.
 */
export function iconForContentType(contentType: string): string {
  const ct = (contentType ?? "").toLowerCase();
  if (ct === "application/pdf") return "📄";
  if (ct.startsWith("video/")) return "🎥";
  if (ct.startsWith("audio/")) return "🎵";
  if (ct.startsWith("text/")) return "📝";
  if (ct.includes("word") || ct.includes("document")) return "📝";
  if (ct.includes("sheet") || ct.includes("excel") || ct.includes("csv")) return "📊";
  if (ct.includes("zip") || ct.includes("archive") || ct.includes("compressed")) return "🗜️";
  if (ct.includes("presentation") || ct.includes("powerpoint")) return "📽️";
  return "📎";
}

/** "3 Dateien" / "1 file" — the count on a folder header. */
export function fileCountLabel(count: number, language: Language): string {
  if (language === "de") return `${count} ${count === 1 ? "Datei" : "Dateien"}`;
  return `${count} ${count === 1 ? "file" : "files"}`;
}
