#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${1:-apps/api/.release.env}"

cd "$ROOT_DIR"

release_version="local-production"
release_commit=""

if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  release_commit="$(git rev-parse --short=12 HEAD 2>/dev/null || true)"
  described_version="$(git describe --tags --always --abbrev=12 2>/dev/null || true)"
  if [[ -n "${described_version}" ]]; then
    release_version="${described_version}"
  fi
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by scripts/update_release_metadata.sh
APP_RELEASE_VERSION=${release_version}
APP_RELEASE_COMMIT=${release_commit}
EOF

echo "Release metadata updated: ${OUTPUT_FILE}"
echo "  APP_RELEASE_VERSION=${release_version}"
echo "  APP_RELEASE_COMMIT=${release_commit}"
