"""construction_reports.customer_id + detach-instead-of-destroy on project delete

Makes construction reports CUSTOMER-owned, with the project as an optional
refinement:

  * Add nullable, indexed ``construction_reports.customer_id`` FK -> customers.id
    (ON DELETE SET NULL, matching ``projects.customer_id``).
  * Backfill it from ``projects.customer_id`` for every report that has a
    project. Reports with no project, or whose project has no customer, stay
    NULL — the only other hint is the free-text ``payload->>'customer'`` and a
    fuzzy match would be permanent (reports are write-once, there is no edit
    endpoint), so those are deliberately left for a human to link.
  * Change ``construction_reports.project_id`` from ON DELETE **CASCADE** to
    ON DELETE **SET NULL**. Projects are hard-deleted (``db.delete(project)``)
    with no ORM cascade in between, so CASCADE meant deleting a project silently
    destroyed the customer's signed field documents. Detaching preserves them.

``report_number`` is intentionally untouched: it stays a per-project sequence
and stays NULL for project-less reports. Issued numbers are already embedded in
rendered PDFs, PDF filenames and dispatched Telegram messages, so re-scoping the
sequence to the customer would invalidate existing artefacts. The
``uq_construction_report_project_number`` constraint therefore also stays as-is —
both Postgres and SQLite treat NULLs as distinct in unique indexes, so the
growing population of (project_id NULL, report_number NULL) rows never collides.

customer_id is left NULLABLE on purpose. Two row classes provably cannot satisfy
NOT NULL today: reports created via the project-less POST /construction-reports
endpoint, and reports on projects whose customer_id is NULL. "Customer is
required" is enforced in the create path / UI instead.

Revision ID: 20260805_0059
Revises: 20260713_0058
Create Date: 2026-08-05 00:00:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "20260805_0059"
down_revision: Union[str, Sequence[str], None] = "20260713_0058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _project_id_fk_name(bind) -> str | None:
    """Reflect the (auto-named) FK on construction_reports.project_id.

    The original table was created with an inline, unnamed ForeignKey, so the
    constraint name was generated by the database (``construction_reports_
    project_id_fkey`` on Postgres). Reflecting avoids hardcoding it.
    """
    for fk in sa.inspect(bind).get_foreign_keys("construction_reports"):
        if fk.get("constrained_columns") == ["project_id"]:
            return fk.get("name")
    return None


def upgrade() -> None:
    bind = op.get_bind()

    # 1. Additive column + index + FK. batch_alter_table keeps this working on
    #    SQLite as well as Postgres.
    with op.batch_alter_table("construction_reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            "ix_construction_reports_customer_id", ["customer_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_construction_reports_customer_id",
            "customers",
            ["customer_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # 2. Backfill from the report's project. Portable correlated subquery.
    op.execute(
        """
        UPDATE construction_reports
           SET customer_id = (
                 SELECT p.customer_id
                   FROM projects p
                  WHERE p.id = construction_reports.project_id
               )
         WHERE project_id IS NOT NULL
           AND customer_id IS NULL
        """
    )

    # 3. project_id: CASCADE -> SET NULL, so deleting a project detaches its
    #    reports instead of destroying them. Postgres only: SQLite cannot drop a
    #    constraint, and the SQLite test schema is built from the models
    #    (Base.metadata.create_all) which already carries SET NULL.
    if bind.dialect.name == "postgresql":
        fk_name = _project_id_fk_name(bind)
        if fk_name:
            op.drop_constraint(fk_name, "construction_reports", type_="foreignkey")
        op.create_foreign_key(
            "fk_construction_reports_project_id",
            "construction_reports",
            "projects",
            ["project_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade() -> None:
    bind = op.get_bind()

    # Restore the original CASCADE behaviour on project_id.
    if bind.dialect.name == "postgresql":
        op.drop_constraint(
            "fk_construction_reports_project_id", "construction_reports", type_="foreignkey"
        )
        op.create_foreign_key(
            "construction_reports_project_id_fkey",
            "construction_reports",
            "projects",
            ["project_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("construction_reports", schema=None) as batch_op:
        batch_op.drop_constraint("fk_construction_reports_customer_id", type_="foreignkey")
        batch_op.drop_index("ix_construction_reports_customer_id")
        batch_op.drop_column("customer_id")
